version: "3.6"

services:
  cloudflared-tunnel:
    container_name: "cloudflared-tunnel"
    image: "cloudflare/cloudflared:latest"
    command: "tunnel run nextcloud"
    environment:
      - "TUNNEL_TOKEN=$TUNNEL_TOKEN"
      - "TUNNEL_POST_QUANTUM=true"
    restart: "unless-stopped"  
